### ISSUE TITLE
No sound for iOs notifications in latest version of toasts

### ISSUE THREAD

**Issue by Bluebeerd** [EgorBo/Toasts.Forms.Plugin#108]
I have seen a number of people complaining about loss of sounds on notifications with iOs and have tried the various remedies, with no success.

I have tried a number of different iPhones, mostly on the latest version 10.2 iOs, but one of them was on a version 8. All of them show the message in the notification area, but there is no sound played.

On Android phones, the plugin happily displays notifications with sound

We are using the latest version of the toasts.forms.plugin (3.1.2) from NuGet in Xamarin.Forms project

Has anyone got any ideas on how to get sound playing on notifications again ?

Also, is there a way of programming a notification to simply vibrate, or just play a sound ?

iOs supports future dating of notifications. Is this possible with this plugin ?

(Sorry my initial question turned into three)

**Comment by adamped** [comment]
@Bluebeerd - in iOS the code inside the plugin to set the sound is just

notification.SoundName = UILocalNotification.DefaultSoundName;

Does this work on iOS 10.1?

Currently there is no way to set Vibrate and Sound On/Off from the plugin side. Happy to accept a PR, otherwise, might take a while for me to get around to it. Just place the options in the INotificationOptions, but it will have to be implemented for each platform.

Future dating isn't possible with this plugin, again it would require an extension to INotificationOptions. I would probably put a nullable DateTime as an option.

**Comment by adamped** [comment]
No response, hence closing this issue.

As a note, future dating is now available with the plugin.
