### ISSUE TITLE
Toast goes trough statusbar with appcompat

### ISSUE THREAD

**Issue by Alagaros** [EgorBo/Toasts.Forms.Plugin#68]
I am writing an Xamarin.Forms app that implements appcompat ([here ](https://blog.xamarin.com/material-design-for-your-xamarin-forms-android-apps/)is how). 

![untitled](https://cloud.githubusercontent.com/assets/16825568/14116409/e4774d1c-f5df-11e5-9232-a24ad3b6da84.png)

However as you can see, this also makes the toast dialog clip trough. A feature to set a offset would be nice if there aren't any other fixes.

**Comment by dcasbonne** [comment]
@EgorBo could you give us some news about that ? 
By the way, did you always support this plugin or not ? (I notice some issue that are 1 year old...)

Thanks!

**Comment by adamped** [comment]
@dcasbonne - thanks for your solution. In the recent couple of months I have been cleaning up issues as best I can but any issues still present aren't actually issues they are feature requests. I don't have much time available for this project but if any solutions are actually provided I am more than happy to include or accept pull requests.

I will look at your custom renderer over the weekend and see if I can integrate / implement in the master branch then push out a nuget package.

**Comment by Alagaros** [comment]
@dcasbonne Thank you for the custom renderer, works perfect!

**Comment by dcasbonne** [comment]
@adamped  Oh it's OK don't worry :) I really understand that you don't spend all your times on this project.
I'm not very easy with pull requests and Git in general so I prefer you to integrate the modification directly in the master branch. (I will try to update the file on the github interface, it seems to be possible to fork and pull request by this way).
I'm almost sure that there is a more "beautiful" way to do that but I'm new to Xamarin and it's not very easy to understand everything in a new framework !

@Alagaros You're welcome ! I'm happy that it works on your devices because I've just tested it on a Nexus 5 (real) and a Nexus 5 in Genymotion.

**Comment by dcasbonne** [comment]
@adamped I think I've succeeded in creating a pull request for this modification. Fell free to update or change the code in the way you want ;)

**Comment by adamped** [comment]
@dcasbonne - thanks for the pull request. Will do some testing over the weekend and make sure it doesn't interfere with non AppCompat Android projects as well, then merge and deploy. Will report back here once its done.

**Comment by dcasbonne** [comment]
@adamped you're welcome! I haven't tried on a non AppCompat project so it's a good idea to try it :-) 
I think it could interfer only if the 0 on the Y axis starts under the statusbar instead of the top of the screen on AppCompat projects.
Let me know how it goes!

**Comment by adamped** [comment]
Fixed in https://www.nuget.org/packages/Toasts.Forms.Plugin/2.0.4
